#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: jupiter的博客

# Short bio or description (displayed in the header)
description: 记录一些技术笔记


host: 0.0.0.0
#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 主页
    url: /
  - name: 项目
    url: /project
  - name: 标签
    url: /tags
  - name: 存档
    url: /archive
  - name: 关于
    url: /about

# Pagination
paginate: 15

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: jupiter.ben@live.com
  facebook:
  flickr:
  github: jupiterben
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  telegram: jupiterben
  pinterest: 
  rss: atom.xml # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: #
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: © 2017 Kiko Now

disqus_shortname: technotes-1
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-143796264-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://blog.nearhub.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: #/blog

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v3.8.4

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

strict_front_matter: true

liquid:
  error_mode: strict

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed #:expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
